### PR TITLE
Feature/accept objects and paths to files

### PR DESCRIPTION
**Pull request by MatteoMolinari93**
#71

### CODE REVIEW

**Comment by levz0r** [comment]
Even though the PR looks great, I didn't have a chance to test it in a CI/CD environment. @dreilly-icf can you confirm it works for you?

**Comment by dreilly-icf** [comment]
@levz0r -

I've set up the secrets and all necessary resources within our pipeline. I can, indeed, confirm it works. 

output:
```
50 | docker run  \
51 | -v $PWD/e2e_testing/cypress:/e2e_testing/cypress \
52 | -w /e2e_testing \
53 | $CYPRESS_DOCKER_IMAGE \
54 | --config baseUrl=$(echo "$CYPRESS_BASE_URL") \
55 | --env PIPELINE=true,E2E_USER_LIST=$CYPRESS_E2E_USER_LIST,GMAIL_CREDENTIAL=$GMAIL_CREDENTIAL,GMAIL_TOKEN=$GMAIL_TOKEN,AWS_REGION=$AWS_REGION,REACT_APP_USER_POOL_ID=$REACT_APP_USER_POOL_ID,REACT_APP_USER_POOL_WEB_CLIENT_ID=$REACT_APP_USER_POOL_WEB_CLIENT_ID,REACT_APP_COGNITO_REDIRECT_URL=$REACT_APP_COGNITO_REDIRECT_URL 2>&1 \
56 | --headless  \
57 | --browser chrome \
58 | --spec "cypress/**/*/email.spec.js" \
59 | \|\| exit 0
60 |
61 | Unable to find image 'XXXXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/automation-image:latest' locally
62 | latest: Pulling from automation-image
```
As you can see, our docker container has spun up successfully. This was part of our build pipeline which retrieves the docker container. After downloading, the run begins:
```
(Run Starting)
--
230 |  
231 | ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
232 | │ Cypress:        9.4.1                                                                          │
233 | │ Browser:        Chrome 97 (headless)                                                           │
234 | │ Node Version:   v16.5.0 (/usr/local/bin/node)                                                  │
235 | │ Specs:          1 found (general/email.spec.js)                                                │
236 | │ Searched:       cypress/**/*/email.spec.js                                                     │
237 | └────────────────────────────────────────────────────────────────────────────────────────────────┘
238 |  
239 | Remove output folder cypress/reports/mocha
240 |  
241 | ────────────────────────────────────────────────────────────────────────────────────────────────────
242 |  
243 | Running:  general/email.spec.js                                                           (1 of 1)
244 |  
245 |  
246 | test the gmail task
247 | emails found
248 | ✓ attempt new auth
249 |  
250 |  
251 | 1 passing (966ms)
252 |  
253 | [mochawesome] Report JSON saved to /e2e_testing/cypress/reports/mocha/.jsons/mochawesome.json
254 |  
255 |  
256 | (Results)
257 |  
258 | ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
259 | │ Tests:        1                                                                                │
260 | │ Passing:      1                                                                                │
261 | │ Failing:      0                                                                                │
262 | │ Pending:      0                                                                                │
263 | │ Skipped:      0                                                                                │
264 | │ Screenshots:  0                                                                                │
265 | │ Video:        false                                                                            │
266 | │ Duration:     0 seconds                                                                        │
267 | │ Spec Ran:     general/email.spec.js                                                            │
268 | └────────────────────────────────────────────────────────────────────────────────────────────────┘
269 |  
270 | Start generate report process
271 | Read and merge jsons from "cypress/reports/mocha/.jsons"
272 | Enhance report
273 | Create HTML report
274 | HTML report successfully created!
275 | /e2e_testing/cypress/reports/mocha/index.html
276 |  
277 | ====================================================================================================
278 |  
279 | (Run Finished)
280 |  
281 |  
282 | Spec                                              Tests  Passing  Failing  Pending  Skipped
283 | ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
284 | │ ✔  general/email.spec.js                    957ms        1        1        -        -        - │
285 | └────────────────────────────────────────────────────────────────────────────────────────────────┘
286 | ✔  All specs passed!                        957ms        1        1        -        -        -

```

So.. there you have it. We did have to make some tweaks, namely, downloading @MatteoMolinari93 feature branch to a local repo and modifying our `package.json` to point to this local directory. 

After all is said and done, though, I hope we've demonstrated the validity of this PR.

**Comment by levz0r** [comment]
Thank you for the detailed information David, and thank you @MatteoMolinari93 for the PR. Merging it now.
P.S It could be really awesome if you could write something about using gmail-tester in a CI/CD environment.

**Comment by dreilly-icf** [comment]
I'd be glad to! If the write-up above is good, I'll work it into a .md file and open a PR for it. It seems most have figured out that they could take the "workaround" approach by retrieving the string and writing to a file, but if my example helps anyone better understand how this is accomplished, I'd be glad to help. 

Thanks for your quick response and, again, for making something that provided real value to my team.

**Comment by dreilly-icf** [comment]
Hi @levz0r  - Sorry to be a bother.. is there a plan to release this change on NPM as a new package version? Not sure what the process entails.

Thanks!

**Comment by levz0r** [comment]
Just released a new version on NPM. Thank you.

**Pull request merged**
