### PR TITLE
Added functionality to work with both paths and json objects

### PR DESCRIPTION
**Pull request by MatteoMolinari93**
Useful when used in cloud environments where you can get the credentials from env variables). Not production ready yet, but a good starting point to add this functionality in the next version

### CODE REVIEW

**Comment by athammer** [comment]
@levz0r How is this PR looking? If there are any issues do you mind updating it @MatteoMolinari93 if not I can take over when I have free time.

**Comment by levz0r** [comment]
Hi, please see my comments regarding this PR:
- Since this is a pretty old PR, there are conflicts that need to be solved first.
- The README.md should reflect the proposed feature.
- The reason this wasn't merged is because there was a refactoring along the new feature (utils.js and other refactoring). I would split this PR into two: the JSON object change and the refactoring separately.

**Comment by MatteoMolinari93** [comment]
@athammer I took a quick look and it seems it needs quite a bit of changes and testing. At the moment I don't have much free time and I'm not using this library actively. Therefore I think it's better if someone else takes over. Would you mind?

**Comment by athammer** [comment]
Yeah I can take over this PR. I can't promise when I'll get it done as the project I'm using the lib for now might not be released but I'll slowly start working on it and if we keep the project I should have this done eventually. 

Thank you @MatteoMolinari93 for your work so far 😃

**Pull request closed without merging**
